allowBuilds:
  '@parcel/watcher': true
  msw: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@tanstack/react-table@9.1.2'
  - '@tanstack/table-core@9.1.2'

overrides:
  brace-expansion: '>=5.0.9'
  fast-uri: '>=3.1.5'
  object-path: '>=0.11.6'
  uuid: '>=11.1.1'

peerDependencyRules:
  allowedVersions:
    eslint: '*'
    typescript: '*'
    react: '*'
    next: '*'
  ignoreMissing:
    - eslint
    - typescript
    - react
    - next

